BandejaBundle\Entity\Deptp:
    type: entity
    table: DEPARTAMENTO
    repositoryClass: BandejaBundle\Repository\DeptoRepository
    id:
        ID_DEPARTAMENTO:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        DESCRIPCION:
            type: string
            length: 255
        ABREV:
            type: string
            length: 10
        DIRECCION:
            type: string
            length: 255
    lifecycleCallbacks: {  }
