BandejaBundle\Entity\DepUsu:
    type: entity
    table: dep_usu
    indexes:
        IDX_A657D367B0349E59:
            columns:
                - FK_ID_DEPTO
        IDX_A657D36755303CDA:
            columns:
                - FK_ID_USUARIO
    id:
        idDepUsu:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_DEP_USU
            generator:
                strategy: IDENTITY
    fields:
        encargado:
            type: boolean
            nullable: false
            options:
                comment: '0: false, 1: true'
                default: '0'
            column: ENCARGADO
        cargo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: CARGO
        fechaC:
            type: datetime
            nullable: false
            column: FECHA_C
        fechaM:
            type: datetime
            nullable: false
            column: FECHA_M
        fechaE:
            type: datetime
            nullable: true
            column: FECHA_E
    manyToOne:
        fkUsuario:
            targetEntity: Usuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                FK_ID_USUARIO:
                    referencedColumnName: ID_USUARIO
            orphanRemoval: false
        fkDepto:
            targetEntity: Departamentos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                FK_ID_DEPTO:
                    referencedColumnName: ID_DEPARTAMENTO
            orphanRemoval: false
    lifecycleCallbacks: {  }
