BandejaBundle\Entity\Usuarios:
    type: entity
    table: USUARIOS
    indexes:
        FK_ID_PERSONA:
            columns:
                - FK_ID_PERSONA
    id:
        idUsuario:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_USUARIO
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: NOMBRE
        contrasena:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: CONTRASENA
        fechaC:
            type: datetime
            nullable: false
            column: FECHA_C
        fechaM:
            type: datetime
            nullable: false
            column: FECHA_M
        fechaE:
            type: datetime
            nullable: true
            column: FECHA_E
        fkPersona:
            type: integer
            nullable: true
            column: FK_ID_PERSONA
#    manyToOne:
#        fkPersona:
#            targetEntity: Personas
#            cascade: {  }
#            fetch: LAZY
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                FK_ID_PERSONA:
#                    referencedColumnName: rut
#            orphanRemoval: false
    oneToMany:
        depUsus:
            targetEntity: DepUsu
            mappedBy: fkUsuario
            fetch: LAZY
    lifecycleCallbacks: {  }
