bandeja_homepage:
    path:     //
    defaults: { _controller: BandejaBundle:Bandeja:index }

login_access:
    path:     /login
    defaults: { _controller: BandejaBundle:Access:login }

logout:
    path:     /logout
    defaults: { _controller: BandejaBundle:Access:logout }

porrecibir_bandeja:
    path:     /porrecibir/{page}
    defaults: { _controller: BandejaBundle:Bandeja:porrecibir, page: 1  }
    requirements:
        page: '\d+'

recibidos_bandeja:
    path:     /recibidos/{page}
    defaults: { _controller: BandejaBundle:Bandeja:recibidos, page: 1  }
    requirements:
        page: '\d+'

despachados_bandeja:
    path:     /despachados/{page}
    defaults: { _controller: BandejaBundle:Bandeja:despachados, page: 1  }
    requirements:
        page: '\d+'

ver_bandeja:
    path:     /ver/{id}
    defaults: { _controller: BandejaBundle:Bandeja:ver, id: 1  }
    requirements:
        id: '\d+'

descargar_bandeja:
    path:     /descargar/{id}
    defaults: { _controller: BandejaBundle:Bandeja:descargarAdjunto  }
    requirements:
        id: '\d+'

nuevo_bandeja:
    path: /nuevo
    defaults: { _controller: BandejaBundle:Bandeja:nuevo }

personas_typeahead:
    path: /personas/{str}
    defaults: { _controller: BandejaBundle:Bandeja:personas }
    methods: [GET]

departamentos_typeahead:
    path: /departamentos/{str}
    defaults: { _controller: BandejaBundle:Bandeja:departamentos }
    methods: [GET]