access_apps:
    path:     /apps
    defaults: { _controller: AccessBundle:Default:apps }

access_homepage:
    path:     //
    defaults: { _controller: AccessBundle:Default:index }

usuario_view:
    path:     //updsuser
    defaults: { _controller: AccessBundle:Usuario:view }