<?php

namespace BandejaBundle\Repository;

/**
 * DeptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeptoRepository extends \Doctrine\ORM\EntityRepository
{
}
